
export const teamAreas = [
    {
        target: "_blank",
        alt: "Andrey Barkov",
        title: "Andrey Barkov",
        href: "https://www.linkedin.com/in/andreybarkov/",
        coords: "342,28,501,217",
        shape: "rect",
    },
    {
        target: "_blank",
        alt: "Bibi Souza",
        title: "Bibi Souza",
        href: "https://www.linkedin.com/in/bibschan/",
        coords: "510,28,662,217",
        shape: "rect",
    },
    {
        target: "_blank",
        alt: "Devreet Dulay",
        title: "Devreet Dulay",
        href: "https://www.linkedin.com/in/devreet-dulay/",
        coords: "674,28,839,217",
        shape: "rect",
    },
    {
        target: "_blank",
        alt: "Dom Beckers",
        title: "Dom Beckers",
        href: "",
        coords: "858,28,1008,217",
        shape: "rect",
    },
    {
        target: "_blank",
        alt: "Fernando Stoelting",
        title: "Fernando Stoelting",
        href: "https://www.linkedin.com/in/fstoelting/",
        coords: "1009,28,1169,217",
        shape: "rect",
    },
    {
        target: "_blank",
        alt: "Gabriela Arno",
        title: "Gabriela Arno",
        href: "https://www.linkedin.com/in/gabriela-arno-a7b55b163/",
        coords: "346,231,500,410",
        shape: "rect",
    },
    {
        target: "_blank",
        alt: "Jackie Ho",
        title: "Jackie Ho",
        href: "https://www.linkedin.com/in/jackiehyho/",
        coords: "512,231,665,410",
        shape: "rect",
    },
    {
        target: "_blank",
        alt: "Kris Krug",
        title: "Kris Krug",
        href: "https://www.linkedin.com/in/kriskrug/",
        coords: "669,231,830,410",
        shape: "rect",
    },
    {
        target: "_blank",
        alt: "Matt Carolan",
        title: "Matt Carolan",
        href: "https://www.linkedin.com/in/matthewcarolan/",
        coords: "840,231,1005,410",
        shape: "rect",
    },
    {
        target: "_blank",
        alt: "Mattias Andersson",
        title: "Mattias Andersson",
        href: "https://www.linkedin.com/in/mattias-andersson/",
        coords: "1005,231,1169,410",
        shape: "rect",
    },
    {
        target: "_blank",
        alt: "Mike Hoff",
        title: "Mike Hoff",
        href: "https://www.linkedin.com/in/mikehoff321/",
        coords: "348,420,497,594",
        shape: "rect",
    },
    {
        target: "_blank",
        alt: "Mohsen Akhavan",
        title: "Mohsen Akhavan",
        href: "https://www.linkedin.com/in/themohsenakhavan/",
        coords: "509,423,668,594",
        shape: "rect",
    },
    {
        target: "_blank",
        alt: "Shanky Silva",
        title: "Shanky Silva",
        href: "",
        coords: "677,421,830,592",
        shape: "rect",
    },
    {
        target: "_blank",
        alt: "Umer Khalid",
        title: "Umer Khalid",
        href: "https://www.linkedin.com/in/umerkhalid1/",
        coords: "844,422,997,596",
        shape: "rect",
    },
    {
        target: "_blank",
        alt: "Will Sheldon",
        title: "Will Sheldon",
        href: "",
        coords: "1011,424,1161,598",
        shape: "rect",
    },
];
